var Descartes=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var Module=moduleArg;var aa="./this.program",ba="",ca;try{ba=(new URL(".",_scriptName)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var l=console.error.bind(console),da=!1;class m{}class ea extends m{constructor(a){super();this.La=a}}function fa(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),ha.push(...a));for(a=ha;a.length>0;)a.shift()(Module)}
function ia(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),ja.push(...a));for(a=ja;a.length>0;)a.shift()(Module)}function n(a){Module.onAbort?.(a);a=`Aborted(${a})`;l(a);da=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ka;async function ma(a){try{var b=await ca(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";}
async function na(a,b){try{var c=await ma(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),n(d)}}async function oa(a){var b=ka;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return na(b,a)}var p,q,pa,u,qa,ra,B,C,sa,D,ja=[],ha=[],F=[],G=0,H=null;
class ta{constructor(a){this.La=a;this.Ia=a-24}init(a,b){C[this.Ia+16>>2]=0;C[this.Ia+4>>2]=a;C[this.Ia+8>>2]=b}}var J=a=>{var b=H?.La;if(!b)return I(0),0;var c=new ta(b);C[c.Ia+16>>2]=b;var d=C[c.Ia+4>>2];if(!d)return I(0),b;for(var e of a){if(e===0||e===d)break;if(ua(e,d,c.Ia+16))return I(e),b}I(d);return b},K={},va=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function wa(a){return this.Fa(C[a>>2])}
var L={},M={},xa={},ya=class extends Error{constructor(a){super(a);this.name="InternalError"}},za=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new ya("Mismatched type converter count");for(var k=0;k<a.length;++k)N(a[k],h[k])}a.forEach(h=>xa[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())M.hasOwnProperty(k)?e[h]=M[k]:(f.push(k),L.hasOwnProperty(k)||(L[k]=[]),L[k].push(()=>{e[h]=M[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},P=a=>{for(var b="";;){var c=D[a++];if(!c)return b;
b+=String.fromCharCode(c)}},Q=class extends Error{constructor(a){super(a);this.name="BindingError"}},Aa=a=>{throw new Q(a);};function Ba(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(a)){if(c.Sa)return;throw new Q(`Cannot register type '${d}' twice`);}M[a]=b;delete xa[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(e=>e()))}function N(a,b,c={}){return Ba(a,b,c)}
var Ca=(a,b,c)=>{switch(b){case 1:return c?d=>u[d]:d=>D[d];case 2:return c?d=>p[d>>1]:d=>B[d>>1];case 4:return c?d=>q[d>>2]:d=>C[d>>2];case 8:return c?d=>pa[d>>3]:d=>sa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Da=[],R=[0,1,,1,null,1,!0,1,!1,1],Ea=[],Fa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=Da.pop()||R.length;R[b]=a;R[b+1]=1;return b}},Ga={name:"emscripten::val",Fa:a=>{if(!a)throw new Q(`Cannot use deleted val. handle = ${a}`);
var b=R[a];if(a>9&&0===--R[a+1]){var c=R[a];R[a]=void 0;var d=Ea[a];d&&(Ea[a]=void 0,d(c));Da.push(a)}return b},Ja:(a,b)=>Fa(b),Ka:wa,Ga:null},Ha=(a,b)=>{switch(b){case 4:return function(c){return this.Fa(qa[c>>2])};case 8:return function(c){return this.Fa(ra[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}};function Ia(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].Ga===void 0)return!0;return!1}
var Ja=(a,b)=>{var c=Module;if(void 0===c[a].Ha){var d=c[a];c[a]=function(...e){if(!c[a].Ha.hasOwnProperty(e.length))throw new Q(`Function '${b}' called with an invalid number of arguments (${e.length}) - expects one of (${c[a].Ha})!`);return c[a].Ha[e.length].apply(this,e)};c[a].Ha=[];c[a].Ha[d.Ma]=d}},Ka=(a,b,c)=>{if(Module.hasOwnProperty(a)){if(void 0===c||void 0!==Module[a].Ha&&void 0!==Module[a].Ha[c])throw new Q(`Cannot register public name '${a}' twice`);Ja(a,a);if(Module[a].Ha.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
Module[a].Ha[c]=b}else Module[a]=b,Module[a].Ma=c},La=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+d*4>>2]);return c},Ma=[],S=a=>{var b=Ma[a];b||(Ma[a]=b=Na.get(a));return b},T=(a,b)=>{a=P(a);var c=S(b);if(typeof c!="function")throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c};class Oa extends Error{}
var Sa=a=>{a=Ra(a);var b=P(a);U(a);return b},Ta=(a,b)=>{function c(f){e[f]||M[f]||(xa[f]?xa[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Oa(`${a}: `+d.map(Sa).join([", "]));},Ua=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},V=(a,b,c)=>{var d=D;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=
c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Va=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Wa=globalThis.TextDecoder&&new TextDecoder,Xa=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Ya=(a=0,b)=>{var c=D;b=Xa(c,a,b,!0);if(b-a>16&&c.buffer&&Wa)return Wa.decode(c.subarray(a,
b));for(var d="";a<b;){var e=c[a++];if(e&128){var f=c[a++]&63;if((e&224)==192)d+=String.fromCharCode((e&31)<<6|f);else{var g=c[a++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|c[a++]&63;e<65536?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Za=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,$a=(a,b,c)=>{a>>=1;b=Xa(B,a,b/2,c);if(b-a>16&&Za)return Za.decode(B.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(B[a]);
return c},ab=(a,b,c=2147483647)=>{if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)p[b>>1]=a.charCodeAt(e),b+=2;p[b>>1]=0;return b-d},bb=a=>a.length*2,cb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=C[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},db=(a,b,c=2147483647)=>{if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;q[b>>2]=f;b+=4;if(b+4>c)break}q[b>>2]=0;return b-d},eb=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>
65535&&c++,b+=4;return b},fb={},hb=()=>{if(!gb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:aa},b;for(b in fb)fb[b]===void 0?delete a[b]:a[b]=fb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);gb=c}return gb},gb;Module.printErr&&(l=Module.printErr);Module.thisProgram&&(aa=Module.thisProgram);var W=Module.preInit;if(W)for(typeof W=="function"&&(Module.preInit=W=[W]);W.length>0;)W.shift()();
var ib,Ra,U,X,I,Y,Z,jb,kb,ua,lb,mb,Na,cc={v:a=>{var b=new ta(a);u[b.Ia+12]==0&&(u[b.Ia+12]=1,G--);u[b.Ia+13]=0;F.push(b);return lb(a)},z:()=>{X(0,0);var a=F.pop();jb(a.La);H=null},a:()=>J([]),k:a=>J([a]),h:(a,b)=>J([a,b]),A:(a,b,c)=>J([a,b,c]),U:()=>{F.length||n("no exception to throw");var a=F.at(-1),b=a.La;u[a.Ia+13]=1;u[a.Ia+12]=0;G++;kb(b);H=new ea(b);throw H;},w:(a,b,c)=>{(new ta(a)).init(b,c);kb(a);H=new ea(a);G++;throw H;},fa:()=>G,c:a=>{H||=new ea(a);throw H;},ca:()=>n(""),ma:a=>{var b=K[a];
delete K[a];var c=b.Ua,d=b.Va,e=b.Na,f=e.map(g=>g.Ra).concat(e.map(g=>g.Xa));za([a],f,g=>{var h={},k,t;for([k,t]of e.entries()){let v=g[k],x=t.Pa,r=t.Qa,y=g[k+e.length],E=t.Wa,O=t.Ya;h[t.Oa]={read:w=>v.Fa(x(r,w)),write:(w,z)=>{var A=[];E(O,w,y.Ja(A,z));va(A)},optional:v.optional}}return[{name:b.name,Fa:v=>{var x={},r;for(r in h)x[r]=h[r].read(v);d(v);return x},Ja:(v,x)=>{for(var r in h)if(!(r in x||h[r].optional))throw new TypeError(`Missing field: "${r}"`);var y=c();for(r in h)h[r].write(y,x[r]);
v!==null&&v.push(d,y);return y},Ka:wa,Ga:d}]})},T:(a,b,c,d,e)=>{b=P(b);d=d===0n;var f=g=>g;if(d){let g=c*8;f=h=>BigInt.asUintN(g,h);e=f(e)}N(a,{name:b,Fa:f,Ja:(g,h)=>{typeof h=="number"&&(h=BigInt(h));return h},Ka:Ca(b,c,!d),Ga:null})},ja:(a,b,c,d)=>{b=P(b);N(a,{name:b,Fa:function(e){return!!e},Ja:function(e,f){return f?c:d},Ka:function(e){return this.Fa(D[e])},Ga:null})},ha:a=>N(a,Ga),S:(a,b,c)=>{b=P(b);N(a,{name:b,Fa:d=>d,Ja:(d,e)=>e,Ka:Ha(b,c),Ga:null})},t:(a,b,c,d,e,f,g)=>{var h=La(b,c);a=P(a);
a=Ua(a);e=T(d,e);Ka(a,function(){Ta(`Cannot call ${a} due to unbound types`,h)},b-1);za([],h,k=>{var t=a;var v=a;k=[k[0],null].concat(k.slice(1));var x=e,r=k.length;if(r<2)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var y=k[1]!==null&&!1,E=Ia(k),O=!k[0].Ta,w=k[0],z=k[1];x=[v,Aa,x,f,va,w.Fa.bind(w),z?.Ja.bind(z)];for(w=2;w<r;++w)z=k[w],x.push(z.Ja.bind(z));if(!E)for(w=y?1:2;w<k.length;++w)k[w].Ga!==null&&x.push(k[w].Ga);E=Ia(k);w=k.length-2;var A=[];
z=["fn"];y&&z.push("thisWired");for(r=0;r<w;++r)A.push(`arg${r}`),z.push(`arg${r}Wired`);A=A.join();z=z.join();A=`return function (${A}) {\n`;E&&(A+="var destructors = [];\n");var Pa=E?"destructors":"null",la="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");y&&(A+=`var thisWired = toClassParamWire(${Pa}, this);\n`);for(r=0;r<w;++r){var Qa=`toArg${r}Wire`;A+=`var arg${r}Wired = ${Qa}(${Pa}, arg${r});\n`;la.push(Qa)}A+=(O||g?"var rv = ":"")+`invoker(${z});\n`;
if(E)A+="runDestructors(destructors);\n";else for(r=y?1:2;r<k.length;++r)y=r===1?"thisWired":"arg"+(r-2)+"Wired",k[r].Ga!==null&&(A+=`${y}_dtor(${y});\n`,la.push(`${y}_dtor`));O&&(A+="var ret = fromRetWire(rv);\nreturn ret;\n");k=(new Function(la,A+"}\n"))(...x);v=Object.defineProperty(k,"name",{value:v});k=b-1;if(!Module.hasOwnProperty(t))throw new ya("Replacing nonexistent public symbol");void 0!==Module[t].Ha&&void 0!==k?Module[t].Ha[k]=v:(Module[t]=v,Module[t].Ma=k);return[]})},C:(a,b,c,d,e)=>
{b=P(b);var f=h=>h;if(d===0){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}N(a,{name:b,Fa:f,Ja:(h,k)=>k,Ka:Ca(b,c,d!==0),Ga:null})},u:(a,b,c)=>{function d(f){return new e(u.buffer,C[f+4>>2],C[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=P(c);N(a,{name:c,Fa:d,Ka:d},{Sa:!0})},ia:(a,b)=>{b=P(b);N(a,{name:b,Fa(c){var d=(d=c+4)?Ya(d,C[c>>2]):"";U(c);return d},Ja(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e=
typeof d=="string";if(!(e||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new Q("Cannot pass non-string to std::string");var f=e?Va(d):d.length;var g=ib(4+f+1),h=g+4;C[g>>2]=f;e?V(d,h,f+1):D.set(d,h);c!==null&&c.push(U,g);return g},Ka:wa,Ga(c){U(c)}})},N:(a,b,c)=>{c=P(c);if(b===2){var d=$a;var e=ab;var f=bb}else d=cb,e=db,f=eb;N(a,{name:c,Fa:g=>{var h=d(g+4,C[g>>2]*b,!0);U(g);return h},Ja:(g,h)=>{if(typeof h!="string")throw new Q(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),
t=ib(4+k+b);C[t>>2]=k/b;e(h,t+4,k+b);g!==null&&g.push(U,t);return t},Ka:wa,Ga(g){U(g)}})},oa:(a,b,c,d,e,f)=>{K[a]={name:P(b),Ua:T(c,d),Va:T(e,f),Na:[]}},na:(a,b,c,d,e,f,g,h,k,t)=>{K[a].Na.push({Oa:P(b),Ra:c,Pa:T(d,e),Qa:f,Xa:g,Wa:T(h,k),Ya:t})},ka:(a,b)=>{b=P(b);N(a,{Ta:!0,name:b,Fa:()=>{},Ja:()=>{}})},$:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();C[a>>2]=Math.max(f,e)*60;q[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${g>=
0?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(V(a,c,17),V(b,d,17)):(V(a,d,17),V(b,c,17))},ga:()=>{n("OOM")},aa:(a,b)=>{var c=0,d=0,e;for(e of hb()){var f=b+c;C[a+d>>2]=f;c+=V(e,f,Infinity)+1;d+=4}return 0},ba:(a,b)=>{var c=hb();C[a>>2]=c.length;a=0;for(var d of c)a+=Va(d)+1;C[b>>2]=a;return 0},la:nb,Y:ob,F:pb,V:qb,q:rb,D:sb,s:tb,Q:ub,r:vb,d:wb,m:xb,g:yb,M:zb,Z:Ab,b:Bb,O:Cb,l:Db,da:Eb,P:Fb,B:Gb,R:Hb,J:Ib,ea:Jb,pa:Kb,K:Lb,i:Mb,n:Nb,p:Ob,qa:Pb,
H:Qb,G:Rb,W:Sb,e:Tb,X:Ub,f:Vb,j:Wb,x:Xb,_:Yb,o:Zb,y:$b,E:ac,I:bc,L:a=>a};function Wb(a,b,c,d,e){var f=Z();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0)}}function wb(a,b){var c=Z();try{return S(a)(b)}catch(d){Y(c);if(!(d instanceof m))throw d;X(1,0)}}function Bb(a,b,c,d){var e=Z();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof m))throw f;X(1,0)}}function Nb(a,b){var c=Z();try{S(a)(b)}catch(d){Y(c);if(!(d instanceof m))throw d;X(1,0)}}
function Xb(a,b,c,d,e,f){var g=Z();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof m))throw h;X(1,0)}}function Mb(a){var b=Z();try{S(a)()}catch(c){Y(b);if(!(c instanceof m))throw c;X(1,0)}}function Vb(a,b,c,d){var e=Z();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof m))throw f;X(1,0)}}function Tb(a,b,c){var d=Z();try{S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}function rb(a,b,c){var d=Z();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}
function xb(a,b,c){var d=Z();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}function yb(a,b,c){var d=Z();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}function Yb(a,b,c,d,e,f,g,h){var k=Z();try{S(a)(b,c,d,e,f,g,h)}catch(t){Y(k);if(!(t instanceof m))throw t;X(1,0)}}function tb(a,b,c,d){var e=Z();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof m))throw f;X(1,0)}}
function vb(a){var b=Z();try{return S(a)()}catch(c){Y(b);if(!(c instanceof m))throw c;X(1,0)}}function zb(a,b,c,d){var e=Z();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof m))throw f;X(1,0)}}function Ab(a,b,c,d,e){var f=Z();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0)}}function $b(a,b,c,d,e,f,g,h){var k=Z();try{S(a)(b,c,d,e,f,g,h)}catch(t){Y(k);if(!(t instanceof m))throw t;X(1,0)}}
function Ob(a,b,c){var d=Z();try{S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}function pb(a,b,c,d){var e=Z();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof m))throw f;X(1,0)}}function Db(a,b,c,d,e){var f=Z();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0)}}function Zb(a,b,c,d,e,f,g){var h=Z();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof m))throw k;X(1,0)}}
function ob(a,b,c){var d=Z();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}function Qb(a,b,c,d,e){var f=Z();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0)}}function Pb(a,b,c,d){var e=Z();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof m))throw f;X(1,0)}}function Rb(a,b,c,d,e,f){var g=Z();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof m))throw h;X(1,0)}}
function Ub(a,b,c,d,e){var f=Z();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0)}}function Kb(a,b,c){var d=Z();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}function Fb(a,b,c,d,e,f){var g=Z();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof m))throw h;X(1,0)}}function sb(a,b,c,d,e){var f=Z();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0)}}
function Gb(a,b,c,d,e,f,g){var h=Z();try{return S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof m))throw k;X(1,0)}}function ac(a,b,c,d,e,f,g,h,k,t,v){var x=Z();try{S(a)(b,c,d,e,f,g,h,k,t,v)}catch(r){Y(x);if(!(r instanceof m))throw r;X(1,0)}}function Sb(a,b,c){var d=Z();try{S(a)(b,c)}catch(e){Y(d);if(!(e instanceof m))throw e;X(1,0)}}function qb(a,b,c,d,e){var f=Z();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0)}}
function Cb(a,b,c,d,e,f){var g=Z();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof m))throw h;X(1,0)}}function nb(a,b){var c=Z();try{return S(a)(b)}catch(d){Y(c);if(!(d instanceof m))throw d;X(1,0)}}function Jb(a,b,c,d,e,f){var g=Z();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof m))throw h;X(1,0)}}function Eb(a,b,c,d,e,f){var g=Z();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof m))throw h;X(1,0)}}
function Hb(a,b,c,d,e,f,g,h){var k=Z();try{return S(a)(b,c,d,e,f,g,h)}catch(t){Y(k);if(!(t instanceof m))throw t;X(1,0)}}function Lb(a,b,c,d,e){var f=Z();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof m))throw g;X(1,0);return 0n}}function ub(a,b,c,d){var e=Z();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof m))throw f;X(1,0)}}function Ib(a,b,c,d,e,f,g,h,k,t,v,x){var r=Z();try{return S(a)(b,c,d,e,f,g,h,k,t,v,x)}catch(y){Y(r);if(!(y instanceof m))throw y;X(1,0)}}
function bc(a,b,c,d,e,f,g,h,k,t,v,x,r,y,E,O){var w=Z();try{S(a)(b,c,d,e,f,g,h,k,t,v,x,r,y,E,O)}catch(z){Y(w);if(!(z instanceof m))throw z;X(1,0)}}var dc;
dc=await (async function(){function a(d){d=dc=d.exports;ib=d.ua;Ra=d.va;U=d.wa;X=d.xa;I=d.ya;Y=d.za;Z=d.Aa;jb=d.Ba;kb=d.Ca;ua=d.Da;lb=d.Ea;mb=d.ra;Na=d.ta;d=mb.buffer;u=new Int8Array(d);p=new Int16Array(d);D=new Uint8Array(d);B=new Uint16Array(d);q=new Int32Array(d);C=new Uint32Array(d);qa=new Float32Array(d);ra=new Float64Array(d);pa=new BigInt64Array(d);sa=new BigUint64Array(d);return dc}var b={a:cc},c=Module.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});ka??=Module.locateFile?
Module.locateFile("wasmLib.wasm",ba):ba+"wasmLib.wasm";return function(d){return a(d.instance)}(await oa(b))}());await (async function(){fa();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));da||(dc.sa(),Module.onRuntimeInitialized?.(),ia())}());
;return Module}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Descartes;module.exports.default=Descartes}else if(typeof define==="function"&&define["amd"])define([],()=>Descartes);
